apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-block-volume-pvc
  namespace: default
spec:
  storageClassName: oci-bv-custom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
